import { index, integer, primaryKey, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const created = { createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() };
const tracked = { ...created, updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() };

export const campuses = sqliteTable("campuses", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), status: text("status").notNull().default("active"), ...tracked }, t => [uniqueIndex("campuses_slug_uq").on(t.slug)]);
export const collegeDomains = sqliteTable("college_domains", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id, { onDelete: "cascade" }), domain: text("domain").notNull(), verified: integer("verified", { mode: "boolean" }).notNull().default(false), ...created }, t => [uniqueIndex("college_domains_domain_uq").on(t.domain)]);
export const users = sqliteTable("users", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), email: text("email").notNull(), emailVerifiedAt: integer("email_verified_at", { mode: "timestamp_ms" }), role: text("role").notNull().default("student"), status: text("status").notNull().default("active"), termsAcceptedAt: integer("terms_accepted_at", { mode: "timestamp_ms" }), deletedAt: integer("deleted_at", { mode: "timestamp_ms" }), ...tracked }, t => [uniqueIndex("users_email_uq").on(t.email), index("users_campus_idx").on(t.campusId, t.status)]);
export const sessions = sqliteTable("sessions", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), revokedAt: integer("revoked_at", { mode: "timestamp_ms" }), ...created }, t => [uniqueIndex("sessions_token_uq").on(t.tokenHash), index("sessions_user_idx").on(t.userId)]);
export const profiles = sqliteTable("profiles", { userId: text("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), handle: text("handle").notNull(), displayName: text("display_name").notNull(), bio: text("bio").notNull().default(""), avatarKey: text("avatar_key"), interests: text("interests").notNull().default("[]"), isPrivate: integer("is_private", { mode: "boolean" }).notNull().default(false), anonymousByDefault: integer("anonymous_by_default", { mode: "boolean" }).notNull().default(true), joinedAt: integer("joined_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() }, t => [uniqueIndex("profiles_handle_uq").on(t.handle)]);
export const follows = sqliteTable("follows", { followerId: text("follower_id").notNull().references(() => users.id, { onDelete: "cascade" }), followedId: text("followed_id").notNull().references(() => users.id, { onDelete: "cascade" }), ...created }, t => [primaryKey({ columns: [t.followerId, t.followedId] }), index("follows_followed_idx").on(t.followedId)]);
export const blocks = sqliteTable("blocks", { blockerId: text("blocker_id").notNull().references(() => users.id, { onDelete: "cascade" }), blockedId: text("blocked_id").notNull().references(() => users.id, { onDelete: "cascade" }), ...created }, t => [primaryKey({ columns: [t.blockerId, t.blockedId] })]);

export const posts = sqliteTable("posts", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), authorId: text("author_id").notNull().references(() => users.id), alias: text("alias"), visibility: text("visibility").notNull().default("anonymous"), body: text("body").notNull(), kind: text("kind").notNull().default("text"), status: text("status").notNull().default("published"), moderationStatus: text("moderation_status").notNull().default("approved"), editedAt: integer("edited_at", { mode: "timestamp_ms" }), deletedAt: integer("deleted_at", { mode: "timestamp_ms" }), ...tracked }, t => [index("posts_campus_created_idx").on(t.campusId, t.createdAt), index("posts_author_idx").on(t.authorId)]);
export const polls = sqliteTable("polls", { id: text("id").primaryKey(), postId: text("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }), closesAt: integer("closes_at", { mode: "timestamp_ms" }), ...created }, t => [uniqueIndex("polls_post_uq").on(t.postId)]);
export const pollOptions = sqliteTable("poll_options", { id: text("id").primaryKey(), pollId: text("poll_id").notNull().references(() => polls.id, { onDelete: "cascade" }), label: text("label").notNull(), position: integer("position").notNull() }, t => [uniqueIndex("poll_options_position_uq").on(t.pollId, t.position)]);
export const pollVotes = sqliteTable("poll_votes", { pollId: text("poll_id").notNull().references(() => polls.id, { onDelete: "cascade" }), optionId: text("option_id").notNull().references(() => pollOptions.id), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), ...created }, t => [primaryKey({ columns: [t.pollId, t.userId] }), index("poll_votes_option_idx").on(t.optionId)]);
export const postLikes = sqliteTable("post_likes", { postId: text("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), ...created }, t => [primaryKey({ columns: [t.postId, t.userId] })]);
export const bookmarks = sqliteTable("bookmarks", { postId: text("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), ...created }, t => [primaryKey({ columns: [t.postId, t.userId] })]);
export const comments = sqliteTable("comments", { id: text("id").primaryKey(), postId: text("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }), authorId: text("author_id").notNull().references(() => users.id), parentId: text("parent_id"), alias: text("alias"), body: text("body").notNull(), status: text("status").notNull().default("published"), deletedAt: integer("deleted_at", { mode: "timestamp_ms" }), ...tracked }, t => [index("comments_post_idx").on(t.postId, t.createdAt), index("comments_parent_idx").on(t.parentId)]);

export const voiceRooms = sqliteTable("voice_rooms", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), hostId: text("host_id").notNull().references(() => users.id), title: text("title").notNull(), topic: text("topic").notNull(), providerRoomId: text("provider_room_id"), status: text("status").notNull().default("live"), endedAt: integer("ended_at", { mode: "timestamp_ms" }), ...tracked }, t => [index("voice_rooms_campus_idx").on(t.campusId, t.status)]);
export const voiceParticipants = sqliteTable("voice_participants", { roomId: text("room_id").notNull().references(() => voiceRooms.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), role: text("role").notNull().default("listener"), muted: integer("muted", { mode: "boolean" }).notNull().default(true), raisedHandAt: integer("raised_hand_at", { mode: "timestamp_ms" }), joinedAt: integer("joined_at", { mode: "timestamp_ms" }).notNull(), leftAt: integer("left_at", { mode: "timestamp_ms" }) }, t => [primaryKey({ columns: [t.roomId, t.userId] })]);
export const conversations = sqliteTable("conversations", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), lastMessageAt: integer("last_message_at", { mode: "timestamp_ms" }), ...tracked }, t => [index("conversations_campus_idx").on(t.campusId)]);
export const conversationMembers = sqliteTable("conversation_members", { conversationId: text("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), mutedUntil: integer("muted_until", { mode: "timestamp_ms" }), lastReadAt: integer("last_read_at", { mode: "timestamp_ms" }), joinedAt: integer("joined_at", { mode: "timestamp_ms" }).notNull() }, t => [primaryKey({ columns: [t.conversationId, t.userId] }), index("conversation_members_user_idx").on(t.userId)]);
export const messages = sqliteTable("messages", { id: text("id").primaryKey(), conversationId: text("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }), senderId: text("sender_id").notNull().references(() => users.id), body: text("body").notNull(), status: text("status").notNull().default("sent"), deletedAt: integer("deleted_at", { mode: "timestamp_ms" }), ...created }, t => [index("messages_conversation_idx").on(t.conversationId, t.createdAt)]);
export const messageReceipts = sqliteTable("message_receipts", { messageId: text("message_id").notNull().references(() => messages.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), deliveredAt: integer("delivered_at", { mode: "timestamp_ms" }), readAt: integer("read_at", { mode: "timestamp_ms" }) }, t => [primaryKey({ columns: [t.messageId, t.userId] })]);

export const events = sqliteTable("events", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), title: text("title").notNull(), description: text("description").notNull(), game: text("game"), capacity: integer("capacity"), startsAt: integer("starts_at", { mode: "timestamp_ms" }).notNull(), status: text("status").notNull().default("published"), ...tracked }, t => [index("events_campus_idx").on(t.campusId, t.startsAt)]);
export const registrations = sqliteTable("registrations", { eventId: text("event_id").notNull().references(() => events.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), status: text("status").notNull().default("registered"), ...created }, t => [primaryKey({ columns: [t.eventId, t.userId] })]);
export const chessMatches = sqliteTable("chess_matches", { id: text("id").primaryKey(), eventId: text("event_id").references(() => events.id), campusId: text("campus_id").notNull().references(() => campuses.id), whiteUserId: text("white_user_id").notNull().references(() => users.id), blackUserId: text("black_user_id").notNull().references(() => users.id), result: text("result"), status: text("status").notNull().default("pending"), suspicious: integer("suspicious", { mode: "boolean" }).notNull().default(false), completedAt: integer("completed_at", { mode: "timestamp_ms" }), ...tracked }, t => [index("chess_matches_campus_idx").on(t.campusId, t.createdAt)]);
export const competitionScores = sqliteTable("competition_scores", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), userId: text("user_id").notNull().references(() => users.id), game: text("game").notNull(), rating: integer("rating").notNull().default(1200), wins: integer("wins").notNull().default(0), losses: integer("losses").notNull().default(0), draws: integer("draws").notNull().default(0), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() }, t => [uniqueIndex("competition_scores_user_game_uq").on(t.userId, t.game), index("competition_scores_rank_idx").on(t.campusId, t.game, t.rating)]);

export const notifications = sqliteTable("notifications", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), actorId: text("actor_id").references(() => users.id), type: text("type").notNull(), entityId: text("entity_id"), body: text("body").notNull(), readAt: integer("read_at", { mode: "timestamp_ms" }), ...created }, t => [index("notifications_user_idx").on(t.userId, t.readAt, t.createdAt)]);
export const reports = sqliteTable("reports", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), reporterId: text("reporter_id").notNull().references(() => users.id), targetType: text("target_type").notNull(), targetId: text("target_id").notNull(), reason: text("reason").notNull(), details: text("details").notNull().default(""), status: text("status").notNull().default("open"), assigneeId: text("assignee_id").references(() => users.id), resolvedAt: integer("resolved_at", { mode: "timestamp_ms" }), ...tracked }, t => [index("reports_queue_idx").on(t.campusId, t.status, t.createdAt)]);
export const moderationDecisions = sqliteTable("moderation_decisions", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), provider: text("provider").notNull(), outcome: text("outcome").notNull(), categories: text("categories").notNull().default("[]"), reason: text("reason").notNull(), reviewerId: text("reviewer_id").references(() => users.id), ...created }, t => [index("moderation_subject_idx").on(t.subjectType, t.subjectId)]);
export const auditLogs = sqliteTable("audit_logs", { id: text("id").primaryKey(), campusId: text("campus_id").references(() => campuses.id), actorId: text("actor_id").references(() => users.id), action: text("action").notNull(), targetType: text("target_type").notNull(), targetId: text("target_id"), metadata: text("metadata").notNull().default("{}"), ...created }, t => [index("audit_campus_idx").on(t.campusId, t.createdAt)]);
export const uploadedMedia = sqliteTable("uploaded_media", { id: text("id").primaryKey(), campusId: text("campus_id").notNull().references(() => campuses.id), ownerId: text("owner_id").notNull().references(() => users.id), objectKey: text("object_key").notNull(), mimeType: text("mime_type").notNull(), byteSize: integer("byte_size").notNull(), status: text("status").notNull().default("pending"), ...created }, t => [uniqueIndex("uploaded_media_key_uq").on(t.objectKey)]);

// === Admin Tables ===
export const adminAccounts = sqliteTable("admin_accounts", {
  id: text("id").primaryKey(),
  email: text("email").notNull(),
  passwordHash: text("password_hash").notNull(),
  displayName: text("display_name").notNull(),
  role: text("role").notNull().default("moderator"), // super_admin | moderator | event_manager | support_admin
  status: text("status").notNull().default("active"), // active | inactive
  lastLoginAt: integer("last_login_at", { mode: "timestamp_ms" }),
  ...tracked,
}, (t) => [uniqueIndex("admin_accounts_email_uq").on(t.email)]);

export const adminSessions = sqliteTable("admin_sessions", {
  id: text("id").primaryKey(),
  adminId: text("admin_id").notNull().references(() => adminAccounts.id, { onDelete: "cascade" }),
  tokenHash: text("token_hash").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  revokedAt: integer("revoked_at", { mode: "timestamp_ms" }),
  ...created,
}, (t) => [uniqueIndex("admin_sessions_token_uq").on(t.tokenHash), index("admin_sessions_admin_idx").on(t.adminId)]);

export const platformSettings = sqliteTable("platform_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull().default(""),
  updatedBy: text("updated_by").references(() => adminAccounts.id),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});
