"use client";
import { useEffect, useState } from "react";
import { CalendarDays } from "lucide-react";
import { useResource } from "@/hooks/use-resource";
import { api } from "@/lib/client-api";
import type { Page, SocialEvent } from "@/lib/social-types";
import { dateLabel, Empty, Failure, Loading } from "./shared";
export function EventsPanel() {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 30_000); return () => clearInterval(timer); }, []);
  const resource = useResource<Page<SocialEvent>>("/api/events"), [busy, setBusy] = useState<string | null>(null), [error, setError] = useState<unknown>(), [extra, setExtra] = useState<SocialEvent[]>([]), [cursor, setCursor] = useState<string | null | undefined>();
  const next = cursor === undefined ? resource.data?.nextCursor : cursor;
  return <section className="echo-events"><div className="section-row"><h2>Events & competitions</h2><CalendarDays /></div>{resource.loading ? <Loading rows={1} /> : resource.error ? <Failure error={resource.error} retry={resource.refresh} /> : resource.data?.items.length ? <div className="room-grid">{[...new Map([...(resource.data?.items ?? []), ...extra].map(item => [item.id, item])).values()].map(event => <article className="room-card" key={event.id}><span className="topic">{event.game || "Campus event"} · {event.status}</span><h3>{event.title}</h3><p>{event.description}</p><p className="muted">{dateLabel(event.startsAt)} · {event.registrations}{event.capacity ? `/${event.capacity}` : ""} registered</p><button className={event.registered ? "secondary" : "primary"} disabled={busy !== null || new Date(event.startsAt).getTime() <= now || (!event.registered && (!!event.capacity && event.registrations >= event.capacity || event.status !== "published"))} onClick={async () => { setBusy(event.id); setError(undefined); try { await api(`/api/events/${event.id}/register`, { method: event.registered ? "DELETE" : "PUT" }); setExtra([]); setCursor(undefined); resource.refresh(); } catch (failure) { setError(failure); } finally { setBusy(null); } }}>{busy === event.id ? "Updating…" : new Date(event.startsAt).getTime() <= now ? (event.registered ? "Registered · started" : "Registration closed") : event.status !== "published" ? "Registration closed" : event.registered ? "Cancel registration" : event.capacity && event.registrations >= event.capacity ? "Event full" : "Register"}</button></article>)}</div> : <Empty title="No upcoming events">Published events from your college will appear here.</Empty>}{Boolean(error) && <Failure error={error} />}{next && <button className="secondary" disabled={busy !== null} onClick={async () => { setBusy("more"); try { const page = await api<Page<SocialEvent>>(`/api/events?cursor=${encodeURIComponent(next)}`); setExtra(items => [...items, ...page.items]); setCursor(page.nextCursor); } catch (failure) { setError(failure); } finally { setBusy(null); } }}>More events</button>}</section>;
}
