"use client";
import { useState } from "react";
import { useResource } from "@/hooks/use-resource";
import { api, jsonBody } from "@/lib/client-api";
import type { Page, PublicPerson, SocialProfile } from "@/lib/social-types";
import { Avatar, Empty, Failure, Loading, Modal, ReportDialog } from "./shared";
import { FeedList } from "./feed";
import { PolicyLinks } from "./policy-links";

export function PeoplePicker({ onSelect, onClose }: { onSelect: (id: string) => void; onClose: () => void }) {
  const [search, setSearch] = useState("");
  const resource = useResource<Page<PublicPerson>>(`/api/profiles?q=${encodeURIComponent(search)}`);
  const [more, setMore] = useState<PublicPerson[]>([]), [cursor, setCursor] = useState<string | null | undefined>(), [busy, setBusy] = useState(false), [error, setError] = useState<unknown>();
  const next = cursor === undefined ? resource.data?.nextCursor : cursor;
  async function load() { if (!next) return; setBusy(true); try { const result = await api<Page<PublicPerson>>(`/api/profiles?q=${encodeURIComponent(search)}&cursor=${encodeURIComponent(next)}`); setMore(items => [...items, ...result.items]); setCursor(result.nextCursor); } catch (failure) { setError(failure); } finally { setBusy(false); } }
  return <Modal title="Discover your campus" onClose={onClose}><div className="echo-form"><label>Find a student<input autoFocus value={search} onChange={e => { setSearch(e.target.value); setMore([]); setCursor(undefined); }} placeholder="Display name or username" /></label></div>{resource.loading ? <Loading rows={2} /> : resource.error ? <Failure error={resource.error} retry={resource.refresh} /> : <div className="people-list">{[...(resource.data?.items ?? []), ...more].map(person => <button key={person.id} className="chat-row" onClick={() => onSelect(person.id)}><Avatar label={person.displayName} /><span><strong>{person.displayName}</strong><small>@{person.handle}{person.isPrivate ? " · Private profile" : ""}</small></span></button>)}{resource.data?.items.length === 0 && <Empty title="No students found">Try another name or username.</Empty>}{next && <button className="secondary" disabled={busy} onClick={load}>Load more students</button>}{Boolean(error) && <Failure error={error} />}</div>}</Modal>;
}
export function ProfilePanel({ personId, onPerson, onMessage, onSignedOut, onUpdated }: { personId: string | null; onPerson: (id: string) => void; onMessage: (id: string) => Promise<void>; onSignedOut: () => void; onUpdated: () => void }) {
  const resource = useResource<SocialProfile>(personId ? `/api/profiles/${personId}` : "/api/profiles/me");
  const [editing, setEditing] = useState(false), [report, setReport] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState<unknown>(), [notice, setNotice] = useState(""), [blocked, setBlocked] = useState(false), [deletion, setDeletion] = useState(false), [confirmation, setConfirmation] = useState("");
  const profile = resource.data;
  async function action(path: string, method: string, body?: unknown) {
    if (busy) return; setBusy(true); setError(undefined); setNotice("");
    try { await api(path, { method, ...(body ? { body: jsonBody(body) } : {}) }); resource.refresh(); onUpdated(); return true; }
    catch (failure) { setError(failure); return false; } finally { setBusy(false); }
  }
  if (resource.loading) return <div className="profile-page"><Loading /></div>;
  if (resource.error) return <div className="profile-page"><Failure error={resource.error} retry={resource.refresh} /></div>;
  if (!profile) return null;
  return <div className="profile-page"><section className="profile-hero"><div className="profile-cover" /><div className="profile-main"><Avatar label={profile.displayName} size={96} /><div><h2>{profile.displayName}</h2><p>@{profile.handle} · {profile.campusName}</p><span className="college-badge">{profile.verified ? "College email verified" : "Email not verified"}</span></div>{profile.isOwn ? <button className="secondary" onClick={() => setEditing(true)}>Edit profile</button> : <button className="secondary" disabled={busy} onClick={() => action(`/api/profiles/${profile.id}/follow`, profile.isFollowing ? "DELETE" : "PUT")}>{profile.isFollowing ? "Unfollow" : "Follow"}</button>}</div><p className="bio">{profile.bio || "A new voice on campus."}</p><div className="profile-stats"><span><b>{profile.followers}</b> Followers</span><span><b>{profile.following}</b> Following</span><span>{profile.isPrivate ? "Private profile" : "Campus profile"}</span></div></section>
    {Boolean(error) && <Failure error={error} />}{notice && <p className="echo-success" role="status">{notice}</p>}
    <div className="profile-content"><section><div className="section-row"><h2>{profile.isOwn ? "Your posts" : "Identified posts"}</h2></div>{profile.canViewPosts ? <FeedList key={profile.id} query={profile.isOwn ? "filter=mine" : `author=${encodeURIComponent(profile.id)}`} onPerson={onPerson} /> : <Empty title="This profile is private">Only existing connections can view identified posts.</Empty>}</section><aside className="profile-controls"><div className="rail-card"><h3>{profile.isOwn ? "Identity & account" : "Connect safely"}</h3>{profile.isOwn ? <><div className="control-row"><span>Anonymous by default</span><b>{profile.anonymousByDefault ? "On" : "Off"}</b></div><p className="muted tiny">Anonymous posts never appear on another student’s public profile view.</p><button className="secondary" onClick={() => setBlocked(true)}>Blocked accounts</button><button className="secondary" disabled={busy} onClick={async () => { if (await action("/api/auth/logout-others", "POST")) setNotice("Other sessions were signed out."); }}>Sign out other sessions</button><button className="secondary" disabled={busy} onClick={async () => { setBusy(true); try { await api("/api/auth/logout", { method: "POST" }); onSignedOut(); } catch (failure) { setError(failure); } finally { setBusy(false); } }}>Sign out</button><h4>Legal and privacy</h4><PolicyLinks includeAppeals label="Account legal and privacy links" /><button className="danger-link" onClick={() => setDeletion(true)}>Request account deletion</button></> : <><button className="primary" disabled={busy} onClick={async () => { setBusy(true); try { await onMessage(profile.id); } catch (failure) { setError(failure); } finally { setBusy(false); } }}>Message</button><button className="secondary" onClick={() => setReport(true)}>Report profile</button><button className="danger-link" disabled={busy} onClick={() => { if (confirm("Block this student? This hides your content from one another and prevents messaging.")) void action(`/api/profiles/${profile.id}/block`, "PUT"); }}>Block account</button></>}</div></aside></div>
    {editing && <EditProfile profile={profile} onClose={() => setEditing(false)} onSaved={() => { setEditing(false); resource.refresh(); onUpdated(); }} />}{report && <ReportDialog targetType="user" targetId={profile.id} onClose={() => setReport(false)} />}{blocked && <BlockedList onClose={() => setBlocked(false)} />}
    {deletion && <Modal title="Request account deletion" busy={busy} onClose={() => setDeletion(false)}><form className="echo-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(undefined); try { await api("/api/account", { method: "DELETE", body: jsonBody({ confirmation }) }); onSignedOut(); } catch (failure) { setError(failure); } finally { setBusy(false); } }}><p>Your account will be deactivated immediately and your content hidden. Data removal from retained safety records and backups follows the operator’s retention process.</p><PolicyLinks label="Deletion policy links" /><label>Type DELETE to confirm<input required value={confirmation} onChange={e => setConfirmation(e.target.value)} /></label>{Boolean(error) && <Failure error={error} />}<button className="primary" disabled={busy || confirmation !== "DELETE"}>Deactivate and request deletion</button></form></Modal>}
  </div>;
}
function EditProfile({ profile, onClose, onSaved }: { profile: SocialProfile; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ displayName: profile.displayName, handle: profile.handle, bio: profile.bio, isPrivate: profile.isPrivate, anonymousByDefault: profile.anonymousByDefault }), [busy, setBusy] = useState(false), [error, setError] = useState<unknown>();
  return <Modal title="Edit your profile" busy={busy} onClose={onClose}><form className="echo-form" onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); try { await api("/api/profiles/me", { method: "PATCH", body: jsonBody(form) }); onSaved(); } catch (failure) { setError(failure); } finally { setBusy(false); } }}><label>Display name<input required maxLength={60} value={form.displayName} onChange={e => setForm({ ...form, displayName: e.target.value })} /></label><label>Username<input required pattern="[a-z0-9_]{3,30}" minLength={3} maxLength={30} value={form.handle} onChange={e => setForm({ ...form, handle: e.target.value.toLowerCase() })} /></label><label>Bio<textarea maxLength={280} value={form.bio} onChange={e => setForm({ ...form, bio: e.target.value })} /></label><label className="check-label"><input type="checkbox" checked={form.anonymousByDefault} onChange={e => setForm({ ...form, anonymousByDefault: e.target.checked })} />Anonymous posting by default</label><label className="check-label"><input type="checkbox" checked={form.isPrivate} onChange={e => setForm({ ...form, isPrivate: e.target.checked })} />Private profile (existing followers retain access)</label>{Boolean(error) && <Failure error={error} />}<button className="primary" disabled={busy}>{busy ? "Saving…" : "Save profile"}</button></form></Modal>;
}
function BlockedList({ onClose }: { onClose: () => void }) {
  const resource = useResource<{ items: PublicPerson[] }>("/api/profiles/me/blocks"), [error, setError] = useState<unknown>(), [busy, setBusy] = useState<string | null>(null);
  return <Modal title="Blocked accounts" onClose={onClose}>{resource.loading ? <Loading rows={1} /> : resource.error ? <Failure error={resource.error} retry={resource.refresh} /> : resource.data?.items.length ? resource.data.items.map(person => <div className="echo-between" key={person.id}><span>{person.displayName}</span><button className="secondary" disabled={busy !== null} onClick={async () => { setBusy(person.id); try { await api(`/api/profiles/${person.id}/block`, { method: "DELETE" }); resource.refresh(); } catch (failure) { setError(failure); } finally { setBusy(null); } }}>Unblock</button></div>) : <Empty title="No blocked accounts" />}{Boolean(error) && <Failure error={error} />}</Modal>;
}
